### PR TITLE
Update NOTICE for 2017

### PR DESCRIPTION
**Pull request by ckadner**
this is a trivial file update to create a silly PR in order to test the Jenkins Pull Request builder

### CODE REVIEW

**Comment by ckadner** [comment]
Test this Jenkins

**Comment by ckadner** [comment]
Test this Jenkins

**Comment by ckadner** [comment]
Test this Jenkins

**Comment by ckadner** [comment]
test this please

**Comment by akchinSTC** [comment]
Build finished.

**Comment by ckadner** [comment]
retest this please

**Comment by akchinSTC** [comment]
Build finished.

**Comment by ApacheBahir** [comment]
Jenkins test build successful

**Comment by lresende** [comment]
@ckadner @akchinSTC  Can we get a link to the build results as well ?

**Comment by ckadner** [comment]
retest this please

**Comment by ApacheBahir** [comment]
Build finished.

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/Apache%20Bahir%20-%20Pull%20Request%20Builder/16/

**Comment by ApacheBahir** [comment]
Hi Luciano,

the Pull Request Builder now does the following:

      when a new PR gets created by a non-admin user then Jenkins will use
      the ApacheBahir user to post "Can one of the admins verify this
      patch?" for which I will receive an email notification
            admin users are determined by a Jenkins setting with list of
            GitHub user names, current admins are you, Alan and myself
      if an admin creates a new PR, Jenkins will start a build right away
      once a build completes the ApacheBahir user will post that the build
      is finished and post a link to the build results
      an admin can whitelist the PR creator
      admins or whitelisted users can trigger (re)builds with the standard
      phrases like "ok to test" or "retest this please"
      new commits pushed to a previously tested PR trigger rebuilds

      things that still don't work:
            including the build status (Success, Failure, Error) in the
            posted comment
            posting build logs or build log portions (i.e. the last 20
            lines of the maven build output)

Best regards,
Christian Kadner
--------------------------------------------------------------------------------------

Software Developer, IBM Spark Technology Center
ckadner@us.ibm.com, (415) 979-1236
--------------------------------------------------------------------------------------

**Comment by ApacheBahir** [comment]
Build finished.

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/Apache%20Bahir%20-%20Pull%20Request%20Builder/23/

**Pull request closed without merging**
