### PR TITLE
[BAHIR-51] MqttStreamSource supports a few important MqttConnectOptions.

### PR DESCRIPTION
**Pull request by ScrapCodes**

### CODE REVIEW

**Comment by swoehrl-mw** [comment]
Change looks good to me. It adds all the important mqtt options and uses sensible defaults.

**Comment by ScrapCodes** [comment]
Thanks @swoehrl-mw, @lresende Please take a look !

**Comment by lresende** [comment]
Would these also apply to the DStream MQTT extension ? if so, should we try to maintain the same level of MQTT supported functionality between the two ?

**Comment by lresende** [comment]
Never mind, #23 is taking care of these changes on the DStream MQTT extension.

**Comment by lresende** [comment]
LGTM

**Comment by ScrapCodes** [comment]
Thanks Luciano !

**Pull request closed without merging**
