### PR TITLE
[BAHIR-101] Initial code of SparkSQL for Cloudant

### PR DESCRIPTION
**Pull request by yanglei99**

### CODE REVIEW

**Comment by ApacheBahir** [comment]
Can one of the admins verify this patch?

**Comment by lresende** [comment]
Please test this Jenkins

**Comment by ckadner** [comment]
ok to test

**Comment by ApacheBahir** [comment]
Build successful

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/40/

**Comment by ckadner** [comment]
@yanglei99 -- Thank you for your PR. Please also include test case(s), example(s) and a README in this PR.

**Comment by lresende** [comment]
ok to test

**Comment by ApacheBahir** [comment]
Build successful

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/41/

**Comment by ApacheBahir** [comment]
Build successful

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/43/

**Comment by ApacheBahir** [comment]
Build successful

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/44/

**Comment by ApacheBahir** [comment]
Build successful

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/45/

**Comment by ApacheBahir** [comment]
Build successful

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/46/

**Comment by ApacheBahir** [comment]
Build successful

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/47/

**Comment by lresende** [comment]
Thank you very much @yanglei99, build is passing, samples and readme looks good...

LGTM, we can take care of tests on a new PR.

Will merge if there are no more comments

**Comment by ApacheBahir** [comment]
Build successful

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/49/

**Comment by yanglei99** [comment]
All the 8 examples (3 in python, 5 in scala) are tested successfully.

**Pull request closed without merging**
