### PR TITLE
IGNORE (another PR builder test)

### PR DESCRIPTION
**Pull request by unknownGitHubUser**
to test PR builder integration

### CODE REVIEW

**Comment by ApacheBahir** [comment]
Can one of the admins verify this patch?

**Comment by ckadner** [comment]
ok to test

**Comment by ApacheBahir** [comment]
Build finished.

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/Apache%20Bahir%20-%20Pull%20Request%20Builder/21/

**Comment by ckadner** [comment]
@lresende -- The Pull Request Builder now does the following:

- when a new PR gets created by non-admin user then Jenkins will use the new `ApacheBahir` user to post `Can one of the admins verify this patch?` for which I will receive an email notification
  - admin users are determined by a Jenkins setting with list of GitHub user names, current admins are you, Alan and myself
- if an admin creates a new PR, Jenkins will start a build right away
- once a build completes the `ApacheBahir` user will post that the build is finished and post a link to the build results
- an admin can whitelist the PR creator
- admins or whitelisted users can trigger (re)builds with phrases like 
  - `Test this Jenkins`
  - `ok to test`
  - `retest this please`
- new commits pushed to a previously tested PR trigger rebuilds
- things that still don't work:
  - [x] including the build status (`Success`, `Failure`, `Error`) in the posted comment
 (_**update: [this works now](https://github.com/apache/bahir/pull/30#issuecomment-271431952)**_ )
  - [ ] posting build logs or build log portions (i.e. the last 20 lines of the maven build output)

**Comment by ApacheBahir** [comment]
Build finished.

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/Apache%20Bahir%20-%20Pull%20Request%20Builder/22/

**Pull request closed without merging**
