### PR TITLE
[MINOR] Fixing the streaming-twitter examples data file path

### PR DESCRIPTION
**Pull request by dheerajdwivedi**

### CODE REVIEW

**Comment by ApacheBahir** [comment]
Can one of the admins verify this patch?

**Comment by lresende** [comment]
ok to test

**Comment by lresende** [comment]
LGTM

**Comment by ApacheBahir** [comment]
Build successful

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/66/

**Pull request closed without merging**
