### PR TITLE
[BAHIR-123] Support latest version of play-json for sql-cloudant

### PR DESCRIPTION
**Pull request by emlaver**
_What_
Updated play json dependency to 2.6.6.

_How_
- Added additional dependencies that used to exist but were removed in latest play-json version
- Fixed json import and calls using latest methods in play-json library

See [BAHIR-123](https://issues.apache.org/jira/browse/BAHIR-123)

### CODE REVIEW

**Comment by ApacheBahir** [comment]
Can one of the admins verify this patch?

**Comment by tedyu** [comment]
lgtm

**Comment by ckadner** [comment]
ok to test

**Comment by ApacheBahir** [comment]
Build failed, see build log for details

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/99/

**Comment by ckadner** [comment]
@emlaver

> `CloudantChangesDFSuite`: 
> `- save dataframe to database using createDBOnSave=true option *** FAILED ***`

> `CloudantAllDocsDFSuite`: 
> `- save dataframe to database using createDBOnSave=true option *** FAILED ***`

**Test failures:** 
```
14:10:05 [INFO] --- scalatest-maven-plugin:1.0:test (test) @ spark-sql-cloudant_2.11 ---
14:10:05 Discovery starting.
14:10:05 
14:10:05 Sql-cloudant tests that require Cloudant databases have been enabled by
14:10:05 the environment variables CLOUDANT_USER and CLOUDANT_PASSWORD.
14:10:05         
14:10:05 Discovery completed in 187 milliseconds.
14:10:05 Run starting. Expected test count is: 22
14:10:05 CloudantOptionSuite:
14:10:09 - invalid api receiver option throws an error message
14:10:09 - empty username option throws an error message
14:10:09 - empty password option throws an error message
14:10:10 - empty databaseName throws an error message
14:10:10 ClientSparkFunSuite:
14:10:10 CloudantChangesDFSuite:
14:10:34 - load and save data from Cloudant database
14:10:36 - load and count data from Cloudant search index
14:10:52 - load data and verify deleted doc is not in results
14:11:12 - load data and count rows in filtered dataframe
14:11:52 - save filtered dataframe to database
14:12:12 - save dataframe to database using createDBOnSave=true option *** FAILED ***
14:12:12   org.apache.bahir.cloudant.common.CloudantException: Database airportcodemapping_df create error: {"error":"file_exists","reason":"The database could not be created, the file already exists."}
14:12:12   at org.apache.bahir.cloudant.common.JsonStoreDataAccess.createDB(JsonStoreDataAccess.scala:143)
14:12:12   at org.apache.bahir.cloudant.CloudantReadWriteRelation.insert(DefaultSource.scala:72)
14:12:12   at org.apache.bahir.cloudant.DefaultSource.createRelation(DefaultSource.scala:172)
14:12:12   at org.apache.bahir.cloudant.DefaultSource.createRelation(DefaultSource.scala:86)
14:12:12   at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:472)
14:12:12   at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
14:12:12   at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
14:12:12   at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
14:12:12   at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
14:12:12   at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
14:12:12   ...
14:12:13 - load and count data from view
14:12:13 - load data from view with MapReduce function
14:12:53 - load data and verify total count of selector, filter, and view option
14:12:53 CloudantSparkSQLSuite:
14:12:56 - verify results from temp view of database n_airportcodemapping
14:12:59 - verify results from temp view of index in n_flight
14:13:00 CloudantAllDocsDFSuite:
14:13:03 - load and save data from Cloudant database
14:13:04 - load and count data from Cloudant search index
14:13:04 - load data and count rows in filtered dataframe
14:13:06 - save filtered dataframe to database
14:13:07 - save dataframe to database using createDBOnSave=true option *** FAILED ***
14:13:07   org.apache.bahir.cloudant.common.CloudantException: Database airportcodemapping_df create error: {"error":"file_exists","reason":"The database could not be created, the file already exists."}
14:13:07   at org.apache.bahir.cloudant.common.JsonStoreDataAccess.createDB(JsonStoreDataAccess.scala:143)
14:13:07   at org.apache.bahir.cloudant.CloudantReadWriteRelation.insert(DefaultSource.scala:72)
14:13:07   at org.apache.bahir.cloudant.DefaultSource.createRelation(DefaultSource.scala:172)
14:13:07   at org.apache.bahir.cloudant.DefaultSource.createRelation(DefaultSource.scala:86)
14:13:07   at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:472)
14:13:07   at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
14:13:07   at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
14:13:07   at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
14:13:07   at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
14:13:07   at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
14:13:07   ...
14:13:07 - load and count data from view
14:13:07 - load data from view with MapReduce function
14:13:08 Run completed in 3 minutes, 2 seconds.
14:13:08 Total number of tests run: 22
14:13:08 Suites: completed 6, aborted 0
14:13:08 Tests: succeeded 20, failed 2, canceled 0, ignored 0, pending 0
14:13:08 *** 2 TESTS FAILED ***
14:13:08 [INFO] ------------------------------------------------------------------------
...
14:13:08 [INFO] Apache Bahir - Spark SQL Cloudant DataSource ....... FAILURE [03:24 min]
...
```

**Comment by ApacheBahir** [comment]
Build failed, see build log for details

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/100/

**Comment by ApacheBahir** [comment]
Build failed, see build log for details

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/101/

**Comment by ckadner** [comment]
@emlaver -- one down, one to go?  :smile: 



> ~`CloudantChangesDFSuite`:~
> ~`- save dataframe to database using createDBOnSave=true option *** FAILED ***`~

> `CloudantAllDocsDFSuite`: 
> `- save dataframe to database using createDBOnSave=true option *** FAILED ***`

**Comment by ApacheBahir** [comment]
Build failed, see build log for details

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/102/

**Comment by ApacheBahir** [comment]
Build successful

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/103/

**Comment by emlaver** [comment]
@ckadner Tests are now passing.

**Comment by ApacheBahir** [comment]
Build successful

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/104/

**Comment by ckadner** [comment]
@emlaver -- can you take care of these deprecation **`WARNING`** messages?

```
13:10:38 [INFO] Compiling 11 Scala sources to /var/lib/jenkins/workspace/bahir_spark_pr_builder/sql-cloudant/target/scala-2.11/classes...
13:10:42 [WARNING] /var/lib/jenkins/workspace/bahir_spark_pr_builder/sql-cloudant/src/main/scala/org/apache/bahir/cloudant/DefaultSource.scala:59: method json in class DataFrameReader is deprecated: Use json(Dataset[String]) instead.
13:10:42 [WARNING]         val df = sqlContext.read.json(cloudantRDD)
13:10:42 [WARNING]                                  ^
13:10:42 [WARNING] /var/lib/jenkins/workspace/bahir_spark_pr_builder/sql-cloudant/src/main/scala/org/apache/bahir/cloudant/DefaultSource.scala:115: method json in class DataFrameReader is deprecated: Use json(Dataset[String]) instead.
13:10:42 [WARNING]             dataFrame = sqlContext.read.json(cloudantRDD)
13:10:42 [WARNING]                                         ^
13:10:42 [WARNING] /var/lib/jenkins/workspace/bahir_spark_pr_builder/sql-cloudant/src/main/scala/org/apache/bahir/cloudant/DefaultSource.scala:121: method json in class DataFrameReader is deprecated: Use json(Dataset[String]) instead.
13:10:42 [WARNING]             sqlContext.read.json(aRDD)
13:10:42 [WARNING]                             ^
13:10:42 [WARNING] /var/lib/jenkins/workspace/bahir_spark_pr_builder/sql-cloudant/src/main/scala/org/apache/bahir/cloudant/DefaultSource.scala:152: method json in class DataFrameReader is deprecated: Use json(Dataset[String]) instead.
13:10:42 [WARNING]               dataFrame = sqlContext.sparkSession.read.json(globalRDD)
13:10:42 [WARNING]                                                        ^
13:10:45 [WARNING] four warnings found
```
```
13:10:46 [INFO] Compiling 11 Scala sources to /var/lib/jenkins/workspace/bahir_spark_pr_builder/sql-cloudant/target/scala-2.11/test-classes...
13:10:49 [WARNING] /var/lib/jenkins/workspace/bahir_spark_pr_builder/sql-cloudant/examples/src/main/scala/org/apache/spark/examples/sql/cloudant/CloudantStreaming.scala:46: method json in class DataFrameReader is deprecated: Use json(Dataset[String]) instead.
13:10:49 [WARNING]       val changesDataFrame = spark.read.json(rdd)
13:10:49 [WARNING]                                         ^
13:10:49 [WARNING] /var/lib/jenkins/workspace/bahir_spark_pr_builder/sql-cloudant/examples/src/main/scala/org/apache/spark/examples/sql/cloudant/CloudantStreaming.scala:67: method registerTempTable in class Dataset is deprecated: Use createOrReplaceTempView(viewName) instead.
13:10:49 [WARNING]           changesDataFrame.registerTempTable("airportcodemapping")
13:10:49 [WARNING]                            ^
13:10:49 [WARNING] /var/lib/jenkins/workspace/bahir_spark_pr_builder/sql-cloudant/examples/src/main/scala/org/apache/spark/examples/sql/cloudant/CloudantStreamingSelector.scala:50: method json in class DataFrameReader is deprecated: Use json(Dataset[String]) instead.
13:10:49 [WARNING]       val changesDataFrame = spark.read.json(rdd)
13:10:49 [WARNING]                                         ^
13:10:52 [WARNING] three warnings found
```

**Comment by emlaver** [comment]
@ckadner Can I handle these `WARNING` messages in separate PR?  I'll need to make changes in classes outside of this PR's scope. 

New JIRA issue: [BAHIR-138](https://issues.apache.org/jira/browse/BAHIR-138)

**Comment by ckadner** [comment]
@emlaver -- Right, I had not realized these deprecation warnings got introduced by another PR prior to this. Thanks for opening a JIRA to track it.

**Comment by ckadner** [comment]
**LGTM**

**Pull request closed without merging**
