### PR TITLE
[BAHIR-120] Akka SQL Streaming build fails with Apache Spark 2.1.1

### PR DESCRIPTION
**Pull request by sbcd90**
This closes BAHIR-120.

### CODE REVIEW

**Comment by ApacheBahir** [comment]
Can one of the admins verify this patch?

**Comment by lresende** [comment]
ok to test

**Comment by ApacheBahir** [comment]
Build failed, see build log for details

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/63/

**Comment by lresende** [comment]
retest

**Comment by ApacheBahir** [comment]
Build successful

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/64/

**Pull request closed without merging**
