### PR TITLE
[BAHIR-23] Build should fail on Checkstyle violations

### PR DESCRIPTION
**Pull request by ckadner**
[BAHIR-23: Build should fail on Checkstyle violation](https://issues.apache.org/jira/browse/BAHIR-23)

Currently the maven build is configured to:
- _fail_ for code style violations in **Scala** files
- _succeed_ despite code style violations in **Java** files
- _exclude_ **Scala** test sources (and examples) from code style checks
- _include_ **Java** test sources (and examples) in code style checks

This PR changes the maven build configuration to 
- _fail_ for code style violations in both **Scala** **_and_** **Java** sources
- _include_ test sources (and examples) in style checks for both **Scala** **_and_** **Java** sources

Additionally cleaning up unsupported `checkstyle` configuration elements (apparently copy-and-pasted from `scalastyle` configuration)

### CODE REVIEW

**Comment by ckadner** [comment]
Build results before this fix:

``` bash
$ mvn -T 1 --fail-at-end -DskipTests=true   scalastyle:check checkstyle:check  | \
    grep "ERROR\|FAILURE\|SUCCESS"
```

``` console
[ERROR] src/main/scala/org/apache/spark/streaming/mqtt/package-info.java:[0] (misc) NewlineAtEndOfFile: File does not end with a newline.
[ERROR] src/main/scala/org/apache/spark/streaming/twitter/package-info.java:[0] (misc) NewlineAtEndOfFile: File does not end with a newline.
[ERROR] examples/src/main/java/org/apache/spark/examples/streaming/twitter/JavaTwitterHashTagJoinSentiments.java:[50] (sizes) LineLength: Line is longer than 100 characters (found 101).
[ERROR] examples/src/main/java/org/apache/spark/examples/streaming/twitter/JavaTwitterHashTagJoinSentiments.java:[100] (sizes) LineLength: Line is longer than 100 characters (found 106).
[ERROR] src/main/scala/org/apache/spark/streaming/zeromq/package-info.java:[0] (misc) NewlineAtEndOfFile: File does not end with a newline.
[ERROR] src/test/java/org/apache/spark/streaming/zeromq/JavaZeroMQStreamSuite.java:[46] (sizes) LineLength: Line is longer than 100 characters (found 107).
[INFO] Apache Bahir - Parent POM .......................... SUCCESS [  1.500 s]
[INFO] Apache Bahir - Spark Streaming Akka ................ SUCCESS [  1.376 s]
[INFO] Apache Bahir - Spark Streaming MQTT ................ SUCCESS [  0.374 s]
[INFO] Apache Bahir - Spark Streaming Twitter ............. SUCCESS [  0.417 s]
[INFO] Apache Bahir - Spark Streaming ZeroMQ .............. SUCCESS [  0.290 s]
[INFO] BUILD SUCCESS
```

`[WARNING] checkstyle:check violations detected but failOnViolation set to false`

After setting `failOnViolation` to `true`:

``` console
$ mvn -T 1 --fail-at-end -DskipTests=true   scalastyle:check checkstyle:check  | \
    grep "ERROR\|FAILURE\|SUCCESS"
```

``` console
[ERROR] src/main/scala/org/apache/spark/streaming/mqtt/package-info.java:[0] (misc) NewlineAtEndOfFile: File does not end with a newline.
[ERROR] src/main/scala/org/apache/spark/streaming/twitter/package-info.java:[0] (misc) NewlineAtEndOfFile: File does not end with a newline.
[ERROR] examples/src/main/java/org/apache/spark/examples/streaming/twitter/JavaTwitterHashTagJoinSentiments.java:[50] (sizes) LineLength: Line is longer than 100 characters (found 101).
[ERROR] examples/src/main/java/org/apache/spark/examples/streaming/twitter/JavaTwitterHashTagJoinSentiments.java:[100] (sizes) LineLength: Line is longer than 100 characters (found 106).
[ERROR] src/main/scala/org/apache/spark/streaming/zeromq/package-info.java:[0] (misc) NewlineAtEndOfFile: File does not end with a newline.
[ERROR] src/test/java/org/apache/spark/streaming/zeromq/JavaZeroMQStreamSuite.java:[46] (sizes) LineLength: Line is longer than 100 characters (found 107).
[INFO] Apache Bahir - Parent POM .......................... SUCCESS [  1.235 s]
[INFO] Apache Bahir - Spark Streaming Akka ................ SUCCESS [  1.111 s]
[INFO] Apache Bahir - Spark Streaming MQTT ................ FAILURE [  0.312 s]
[INFO] Apache Bahir - Spark Streaming Twitter ............. FAILURE [  0.341 s]
[INFO] Apache Bahir - Spark Streaming ZeroMQ .............. FAILURE [  0.262 s]
[INFO] BUILD FAILURE
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default-cli) on project spark-streaming-mqtt_2.11: You have 1 Checkstyle violation. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default-cli) on project spark-streaming-twitter_2.11: You have 3 Checkstyle violations. -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default-cli) on project spark-streaming-zeromq_2.11: You have 2 Checkstyle violations. -> [Help 1]
[ERROR] ...
```

And after addressing the code style violations in the Java sources:

``` bash
$ mvn -T 1 --fail-at-end -DskipTests=true   scalastyle:check checkstyle:check  | \
    grep -i "error\|style\|fail\|success"
```

``` console
[INFO] --- scalastyle-maven-plugin:0.8.0:check (default-cli) @ bahir-parent_2.11 ---
Saving to outputFile=/Users/ckadner/Projects/bahir_ckadner/target/scalastyle-output.xml
Found 0 errors
[INFO] --- maven-checkstyle-plugin:2.17:check (default-cli) @ bahir-parent_2.11 ---
[INFO] --- scalastyle-maven-plugin:0.8.0:check (default-cli) @ spark-streaming-akka_2.11 ---
Saving to outputFile=/Users/ckadner/Projects/bahir_ckadner/streaming-akka/target/scalastyle-output.xml
Found 0 errors
[INFO] --- maven-checkstyle-plugin:2.17:check (default-cli) @ spark-streaming-akka_2.11 ---
[INFO] --- scalastyle-maven-plugin:0.8.0:check (default-cli) @ spark-streaming-mqtt_2.11 ---
Saving to outputFile=/Users/ckadner/Projects/bahir_ckadner/streaming-mqtt/target/scalastyle-output.xml
Found 0 errors
[INFO] --- maven-checkstyle-plugin:2.17:check (default-cli) @ spark-streaming-mqtt_2.11 ---
[INFO] --- scalastyle-maven-plugin:0.8.0:check (default-cli) @ spark-streaming-twitter_2.11 ---
Saving to outputFile=/Users/ckadner/Projects/bahir_ckadner/streaming-twitter/target/scalastyle-output.xml
Found 0 errors
[INFO] --- maven-checkstyle-plugin:2.17:check (default-cli) @ spark-streaming-twitter_2.11 ---
[INFO] --- scalastyle-maven-plugin:0.8.0:check (default-cli) @ spark-streaming-zeromq_2.11 ---
Saving to outputFile=/Users/ckadner/Projects/bahir_ckadner/streaming-zeromq/target/scalastyle-output.xml
Found 0 errors
[INFO] --- maven-checkstyle-plugin:2.17:check (default-cli) @ spark-streaming-zeromq_2.11 ---
[INFO] Apache Bahir - Parent POM .......................... SUCCESS [  1.168 s]
[INFO] Apache Bahir - Spark Streaming Akka ................ SUCCESS [  1.088 s]
[INFO] Apache Bahir - Spark Streaming MQTT ................ SUCCESS [  0.324 s]
[INFO] Apache Bahir - Spark Streaming Twitter ............. SUCCESS [  0.367 s]
[INFO] Apache Bahir - Spark Streaming ZeroMQ .............. SUCCESS [  0.241 s]
[INFO] BUILD SUCCESS
```

**Comment by deroneriksson** [comment]
LGTM.

Verified behavior on OS X 10.10.5, Java 1.8.0_66, Maven 3.3.9.

Commit d655923 has build fail on checkstyle violations.
Commit acf3ed0 fixes style issues.
After this, build succeeds.

Updating a Java line in JavaActorWordCount.java to 100+ characters correctly causes build to fail.
Updating a Scala line in ActorWordCount.scala to 100+ characters correctly causes build to fail.

**Comment by ckadner** [comment]
@deroneriksson Thank you for you careful review!

@lresende Do you have comments, concerns, suggestions?

**Comment by lresende** [comment]
LGTM

**Comment by ckadner** [comment]
@lresende Thanks for merging this PR into master with commit [d6770f8](https://github.com/apache/bahir/commit/d6770f833ec723f24ea452c11fd102624d12c3f2).

Closing  this PR.

**Pull request closed without merging**
