### PR TITLE
[BAHIR-46] Handle re-delivery of message in MQTT structured streaming source.[WIP]

### PR DESCRIPTION
**Pull request by ScrapCodes**
Also offset is a Long in Spark we should stick to that.

### CODE REVIEW

**Comment by ScrapCodes** [comment]
@frreiss I have tried to handle re-delivery case and now message is stored to disk as soon as it arrives.

**Comment by lresende** [comment]
@ScrapCodes, Is this still a WIP?

**Comment by ScrapCodes** [comment]
Yes, I am awaiting the fixing of SPARK-16963.

**Comment by lresende** [comment]
@ScrapCodes  Now that [SPARK-16963](https://issues.apache.org/jira/browse/SPARK-16963) is resolved, could you please rebase and let us know if this is ok to merge.

**Comment by ApacheBahir** [comment]
Build successful

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/Apache%20Bahir%20-%20Pull%20Request%20Builder/33/

**Comment by ScrapCodes** [comment]
I will update this soon.

**Comment by lresende** [comment]
ping @ScrapCodes

**Comment by ScrapCodes** [comment]
Sorry for the delay, @lresende.

**Pull request closed without merging**
