### PR TITLE
Fixes for akka example

### PR DESCRIPTION
**Pull request by scottkwalker**
Hi, 
I was looking at the streaming-akka example in Intellij IDE and it suggested some minor fixes:
- use string interpolation
- the mutable collection must be prefixed as mutable

Best regards,

Scott

### CODE REVIEW

**Comment by ApacheBahir** [comment]
Can one of the admins verify this patch?

**Comment by ckadner** [comment]
@scottkwalker -- thank you. LGTM. I will merge this tonight

**Comment by ApacheBahir** [comment]
Can one of the admins verify this patch?

**Comment by ckadner** [comment]
@scottkwalker -- apologies for the delay, thanks for your code style fix!

**Pull request closed without merging**
