### PR TITLE
[BAHIR-141] Added support for passing json cred file as byte array

### PR DESCRIPTION
**Pull request by ankitagr2312**

### CODE REVIEW

**Comment by ApacheBahir** [comment]
Can one of the admins verify this patch?

**Comment by tedyu** [comment]
Is it possible to add a test ?

**Comment by surajnayak** [comment]
@ankitagr2312, I hope you need to add formatting rules/template to the IDE. Any reason to change the spark.close to spark.stop in the test suits?

**Comment by ankitagr2312** [comment]
Yup... will do that and send a pull request again.

**Comment by lresende** [comment]
ok to test

**Comment by ApacheBahir** [comment]
:red_circle: Build failed, see build log for details

**Comment by ApacheBahir** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://169.45.79.58:8080/job/bahir_spark_pr_builder/151/

**Comment by lukasz-antoniak** [comment]
@ankitagr2312: Since the last update is already one year old, do you plan to
work on this JIRA ticket and pull request? If not, do you agree that I take it from here?

1) I think that `ServiceAccountCredentials` could be divided into two separate implementations of `SparkGPCCredentials` interface. First implementation `JsonConfigCredentials` would accept either path to JSON file or binary content. Second implementation `EmailPrivateKeyCredentials` would require passing email address and path to P12 key or binary content of the key.

2) Can you revert to original formatting of lines that you did not mean to modify?

3) Update the _README.md_ to include new feature? Undocumented feature is not a feature :).

**Comment by lukasz-antoniak** [comment]
Follow up in PR #82.

**Pull request closed without merging**
